apiVersion: v1
kind: LimitRange
metadata:
    name: q-limit-range
    namespace: quotas
spec:
   limits:
   - default:
       cpu: "200m"
       memory: "512Mi"
     defaultRequest:
       cpu: "100m"
       memory: "256Mi"
     type: Container
